---
version: 2
workflows:
  version: 2
  test:
    jobs:
      - format_check
      - validation_check

jobs:
  format_check:
    docker:
      - image: "hashicorp/terraform:0.12.17"
    steps:
      - checkout
      - run:
          name: Check terraform formatting
          command: terraform fmt -check=true -write=false
  validation_check:
    working_directory: ~
    docker:
      - image: "hashicorp/terraform:0.12.17"
    steps:
      - checkout
      - run:
          name: create fake license file
          command: touch ~/fake.rli
      - run:
          name: create fake google creds.json
          command: touch ~/fake_creds.json
      - run:
          name: create fake certificate
          command: touch ~/fake.cer
      - run:
          name: create fake tfvars file and provider stub
          command: echo -e "license_file = \"~/fake.rli\"\ncredentials_file = \"~/fake_creds.json\"\ndnszone = \"fake-zone\"\nproject = \"fake-project\"\n" > terraform.tfvars
      - run:
          name: create provider stub
          command: echo -e "provider \"google\" {\n  region = \"us-west-2\"\n}\n" > provider.tf
      - run:
          name: init configs and check if valid
          command: terraform init && terraform validate
